# Generated by Django 5.1.7 on 2026-02-04 06:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MsCountry",
            fields=[
                (
                    "country_code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                (
                    "country_name_ja",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "country_name_en",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
            ],
            options={
                "verbose_name": "国マスタ",
                "verbose_name_plural": "国マスタ",
                "db_table": "ms_country",
            },
        ),
        migrations.CreateModel(
            name="MsInputType",
            fields=[
                (
                    "input_type_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("input_type_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("input_type_usecase_class_path", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "データ入力種別マスタ",
                "verbose_name_plural": "データ入力種別マスタ",
                "db_table": "ms_input_type",
            },
        ),
        migrations.CreateModel(
            name="MsRegisterPolicy",
            fields=[
                (
                    "policy_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("policy_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("policy_processor_class_path", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "データ登録/更新ポリシーマスタ",
                "verbose_name_plural": "データ登録/更新ポリシーマスタ",
                "db_table": "ms_register_policy",
            },
        ),
        migrations.CreateModel(
            name="MsInputDef",
            fields=[
                ("input_id", models.AutoField(primary_key=True, serialize=False)),
                ("input_name", models.CharField(max_length=40)),
                ("target_model_name", models.CharField(max_length=40)),
                ("delimiter", models.CharField(blank=True, max_length=5, null=True)),
                ("has_header", models.BooleanField(blank=True, null=True)),
                (
                    "insert_duplication_lookup_fields",
                    models.JSONField(blank=True, null=True),
                ),
                (
                    "input_type",
                    models.ForeignKey(
                        db_column="input_type_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.msinputtype",
                    ),
                ),
                (
                    "register_policy",
                    models.ForeignKey(
                        db_column="policy_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.msregisterpolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "データ入力定義マスタ",
                "verbose_name_plural": "データ入力定義マスタ",
                "db_table": "ms_input_def",
            },
        ),
        migrations.CreateModel(
            name="RunResultRecord",
            fields=[
                (
                    "run_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mode", models.CharField(max_length=20)),
                ("source", models.CharField(max_length=20)),
                (
                    "input_def_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("csv_def_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "target_model",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "executed_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("invoked_by", models.CharField(blank=True, max_length=100, null=True)),
                ("input_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "input_fingerprint",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("tags_json", models.JSONField(blank=True, null=True)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(max_length=30)),
                ("total_rows", models.IntegerField(default=0)),
                ("parsed_rows", models.IntegerField(default=0)),
                ("fk_resolved_rows", models.IntegerField(default=0)),
                ("processed_rows", models.IntegerField(default=0)),
                ("inserted_rows", models.IntegerField(default=0)),
                ("updated_rows", models.IntegerField(default=0)),
                ("skipped_rows", models.IntegerField(default=0)),
                ("error_rows", models.IntegerField(default=0)),
                ("info_count", models.IntegerField(default=0)),
                ("warn_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("summary_message", models.TextField(blank=True, null=True)),
                (
                    "exception_type",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("exception_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "処理実行結果管理",
                "verbose_name_plural": "処理実行結果管理",
                "db_table": "tr_run_result",
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="tr_run_resu_created_23057a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="tr_run_resu_status_66d4c1_idx"
                    ),
                    models.Index(
                        fields=["input_def_id"], name="tr_run_resu_input_d_a88efe_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IssueRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("domain", models.CharField(max_length=50)),
                ("phase", models.CharField(max_length=100)),
                ("severity", models.CharField(max_length=10)),
                ("code", models.CharField(max_length=200)),
                ("row_index", models.IntegerField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("skip_scope", models.CharField(default="NONE", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="common.runresultrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "処理実行結果管理詳細",
                "verbose_name_plural": "処理実行結果管理詳細",
                "db_table": "tr_issue",
            },
        ),
        migrations.CreateModel(
            name="IssueContextRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contexts",
                        to="common.issuerecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "処理実行結果管理詳細コンテキスト",
                "verbose_name_plural": "処理実行結果詳細コンテキスト",
                "db_table": "tr_issue_context",
                "indexes": [
                    models.Index(fields=["key"], name="tr_issue_co_key_dfd5bb_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="MsInputColumnDef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_order", models.PositiveSmallIntegerField()),
                ("input_source_key", models.CharField(max_length=40)),
                (
                    "model_target_field_name",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("is_fk_flag", models.BooleanField()),
                ("is_lookup_only", models.BooleanField(default=False)),
                ("input_lookup_fields", models.JSONField(blank=True, null=True)),
                (
                    "fk_target_model",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "fk_target_field",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("fk_lookup_fields", models.JSONField(blank=True, null=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "input_id",
                    models.ForeignKey(
                        db_column="input_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.msinputdef",
                    ),
                ),
            ],
            options={
                "verbose_name": "データ入力定義カラムマスタ",
                "verbose_name_plural": "データ入力定義カラムマスタ",
                "db_table": "ms_input_column_def",
                "unique_together": {("input_id", "column_order")},
            },
        ),
        migrations.CreateModel(
            name="MsInputPreprocessDef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.PositiveIntegerField(default=1)),
                ("preprocess_key", models.CharField(max_length=100)),
                ("is_enabled", models.BooleanField(default=True)),
                ("params_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "input_id",
                    models.ForeignKey(
                        db_column="input_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.msinputdef",
                    ),
                ),
            ],
            options={
                "verbose_name": "データ入力定義前処理マスタ",
                "verbose_name_plural": "データ入力定義前処理マスタ",
                "db_table": "ms_input_preprocess_def",
                "indexes": [
                    models.Index(
                        fields=["input_id", "seq"],
                        name="ms_input_pr_input_i_d60aca_idx",
                    )
                ],
                "unique_together": {("input_id", "seq")},
            },
        ),
        migrations.CreateModel(
            name="MsRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_code", models.CharField(max_length=6)),
                ("region_name_ja", models.CharField(max_length=100)),
                (
                    "region_name_en",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.mscountry",
                    ),
                ),
            ],
            options={
                "verbose_name": "地域マスタ",
                "verbose_name_plural": "地域マスタ",
                "db_table": "ms_region",
                "unique_together": {("country", "region_code")},
            },
        ),
        migrations.AddIndex(
            model_name="issuerecord",
            index=models.Index(fields=["severity"], name="tr_issue_severit_8d02c3_idx"),
        ),
        migrations.AddIndex(
            model_name="issuerecord",
            index=models.Index(fields=["code"], name="tr_issue_code_4528c9_idx"),
        ),
        migrations.AddIndex(
            model_name="issuerecord",
            index=models.Index(fields=["phase"], name="tr_issue_phase_7e23ad_idx"),
        ),
    ]
