# Generated by Django 5.1.7 on 2026-02-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestNameList",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40)),
                ("bort_in", models.CharField(max_length=40)),
                ("country", models.CharField(max_length=40)),
            ],
        ),
    ]
