# Generated by Django 5.1.7 on 2026-02-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_testnamelist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testnamelist",
            options={
                "verbose_name": "テスト用名簿",
                "verbose_name_plural": "テスト用名簿",
            },
        ),
        migrations.AlterField(
            model_name="msinputtype",
            name="input_type_usecase_class_path",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="msregisterpolicy",
            name="policy_processor_class_path",
            field=models.CharField(max_length=300),
        ),
    ]
