# Generated by Django 5.1.7 on 2026-02-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_testnamelist_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="testnamelist",
            table="test_name_list",
        ),
    ]
