# Generated by Django 5.1.7 on 2026-02-04 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_testnamelist_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testnamelist",
            name="bort_in",
        ),
        migrations.AddField(
            model_name="testnamelist",
            name="born_in",
            field=models.DateTimeField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="testnamelist",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.mscountry"
            ),
        ),
        migrations.AlterField(
            model_name="testnamelist",
            name="name",
            field=models.IntegerField(blank=True, max_length=40, null=True),
        ),
    ]
