# Generated by Django 5.1.7 on 2026-02-05 12:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_remove_testnamelist_bort_in_testnamelist_born_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuecontextrecord",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="testnamelist",
            name="born_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testnamelist",
            name="name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
