# Generated by Django 5.1.7 on 2026-02-05 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_alter_issuecontextrecord_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testnamelist",
            name="country",
            field=models.ForeignKey(
                db_column="country_code",
                on_delete=django.db.models.deletion.CASCADE,
                to="common.mscountry",
            ),
        ),
    ]
