# Generated by Django 5.1.7 on 2026-02-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_alter_testnamelist_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testnamelist",
            name="born_in",
            field=models.DateField(blank=True, null=True),
        ),
    ]
