# Generated by Django 5.1.7 on 2026-02-10 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_alter_testnamelist_born_in"),
    ]

    operations = [
        migrations.CreateModel(
            name="MsInputNormilizerStepDef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.PositiveIntegerField(default=1)),
                ("normalizer_step_key", models.CharField(max_length=100)),
                ("is_enabled", models.BooleanField(default=True)),
                ("params_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "input_id",
                    models.ForeignKey(
                        db_column="input_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.msinputdef",
                    ),
                ),
            ],
            options={
                "verbose_name": "データ入力定義前処理マスタ",
                "verbose_name_plural": "データ入力定義前処理マスタ",
                "db_table": "ms_input_normilizer_step_def",
            },
        ),
        migrations.DeleteModel(
            name="MsInputPreprocessDef",
        ),
        migrations.AddIndex(
            model_name="msinputnormilizerstepdef",
            index=models.Index(
                fields=["input_id", "seq"], name="ms_input_no_input_i_c04438_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="msinputnormilizerstepdef",
            unique_together={("input_id", "seq")},
        ),
    ]
