# Generated by Django 5.1.7 on 2026-02-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "common",
            "0009_msinputnormilizerstepdef_delete_msinputpreprocessdef_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testnamelist",
            name="execute_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
